### ISSUE TITLE
sing-box

### ISSUE THREAD

**Issue by linehman** [mahanmi/iran-clash-example#2]
سلام وقت بخیر
آیا امکانش هست که تمپلیت با کلاینت sing-box هم سازگار بشه؟

http://sing-box.sagernet.org/examples/clash-api/

در حال حاضر هنگام ایمپورت خطای زیر نمایش داده می شه که بنظرم بخاطر عدم سازگاری فایل json هست.
decode config: invalid character 'd' looking for begening of value

این کلاینت برای ios هم موجوده.

**Comment by mahanmi** [comment]
سلام
واقعیتش من خودم هم درست بلد نیستم از sing-box استفاده کنم اگر ممکنه تلگرام بهم پیام بدید @mahan_m_i
